import json
import os
import re
from datetime import datetime
from fpdf import FPDF
from fpdf.enums import XPos, YPos

# Paths
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
REPORT_JSON = os.path.join(BASE_DIR, "audit_report.json")
OUTPUT_PDF = os.path.join(BASE_DIR, "DPDP_Compliance_Report.pdf")

class PDFReport(FPDF):
    def header(self):
        # Company Logo/Branding
        self.set_fill_color(0, 47, 167) # LexGuard Blue
        self.rect(0, 0, 210, 40, 'F')
        
        self.set_y(15)
        self.set_font("Helvetica", "B", 22)
        self.set_text_color(255, 255, 255)
        self.cell(0, 10, "LexGuard AI Audit Report", border=0, align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        
        self.set_font("Helvetica", "", 10)
        self.cell(0, 5, "DPDP Act 2023 - Deep Compliance Analysis", border=0, align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.ln(15)

    def footer(self):
        self.set_y(-25)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(100, 100, 100)
        self.draw_line(10, self.get_y(), 200, self.get_y())
        self.ln(2)
        
        disclaimer = "This report is generated by LexGuard AI for informational purposes. It does not constitute legal advice."
        self.cell(0, 5, disclaimer, align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        
        self.set_font("Helvetica", "B", 8)
        self.cell(0, 5, f"Confidential | Page {self.page_no()} of {{nb}}", align="C")

    def draw_line(self, x1, y1, x2, y2):
        self.line(x1, y1, x2, y2)

    def section_title(self, label):
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(0, 47, 167)
        self.cell(0, 10, label, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.draw_line(10, self.get_y(), 60, self.get_y())
        self.ln(5)

def clean_text(text):
    """Deep clean text for PDF compatibility without losing information."""
    if not text:
        return "N/A"
    # Replace common Unicode symbols that break Latin-1 if we fall back,
    # but since we use fpdf2, we just ensure it's a string.
    text = text.replace("**", "").replace("_", "").replace("`", "'")
    # Remove excessive newlines
    text = re.sub(r'\n{3,}', '\n\n', text)
    return text.strip()

def extract_section_and_fix(text: str):
    """More robust parsing for audit results."""
    section = "General Compliance"
    fix = text
    
    # Try to extract Section
    sec_match = re.search(r'(?i)(?:Section|Act Section|Reference)[\*:\s]+([0-9a-zA-Z\(\)\.\s,]+)', text)
    if sec_match:
        section = f"DPDP {sec_match.group(1).strip()}"
        
    # Try to extract Suggested Correction
    fix_match = re.search(r'(?i)(?:Suggested Correction|Fix|Correction|Remediation)[\*:\s]+(.*)', text, re.DOTALL)
    if fix_match:
        fix = fix_match.group(1).strip()
    
    return section, clean_text(fix)

def generate_report(report_data=None, report_json_path=REPORT_JSON, output_pdf_path=OUTPUT_PDF):
    if report_data is not None:
        data = report_data
    else:
        if not os.path.exists(report_json_path):
            return None
        with open(report_json_path, 'r', encoding='utf-8') as f:
            data = json.load(f)

    pdf = PDFReport()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)

    # 1. Executive Summary
    pdf.section_title("Executive Summary")
    
    # Metadata table
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_fill_color(245, 247, 251)
    
    # Fix: Use actual UTC time as labeled
    from datetime import timezone
    utc_now = datetime.now(timezone.utc).strftime("%B %d, %Y | %H:%M UTC")
    
    col_width = 45
    pdf.cell(col_width, 8, "Date Generated:", border=1, fill=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 8, utc_now, border=1, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    
    # Fix: Mutually exclusive risk counts to prevent negative results
    high = 0
    med = 0
    low = 0
    for i in data:
        status_raw = i.get("status", "Low")
        audit_raw = i.get("audit_result", "")
        if "High" in status_raw or "Non-Compliant" in audit_raw:
            high += 1
        elif "Medium" in status_raw:
            med += 1
        else:
            low += 1
    
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(col_width, 8, "Total Clauses Checked:", border=1, fill=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 8, str(len(data)), border=1, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    
    pdf.ln(5)

    # Risk Scorecard
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Compliance Scorecard", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    
    # Horizontal Bars for Risk
    bar_max_width = 180
    def draw_stat(label, count, color_tuple):
        percentage = (count / len(data)) if len(data) > 0 else 0
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(50, 50, 50)
        pdf.cell(40, 8, f"{label}: {count}", new_x=XPos.RIGHT)
        
        # Background bar
        curr_x, curr_y = pdf.get_x(), pdf.get_y() + 2
        pdf.set_fill_color(240, 240, 240)
        pdf.rect(curr_x, curr_y, bar_max_width - 50, 4, 'F')
        # Foreground bar
        pdf.set_fill_color(*color_tuple)
        pdf.rect(curr_x, curr_y, (bar_max_width - 50) * percentage, 4, 'F')
        pdf.ln(8)

    draw_stat("High Risk", high, (220, 38, 38))
    draw_stat("Medium Risk", med, (217, 119, 6))
    draw_stat("Low Risk", low, (22, 163, 74))
    
    pdf.set_text_color(0, 0, 0)
    pdf.ln(10)

    # 2. Detailed Findings
    pdf.section_title("Detailed Audit Findings")

    for idx, item in enumerate(data, 1):
        with pdf.unbreakable():
            status_raw = item.get("status", "Low")
            audit_raw = item.get("audit_result", "")
            is_high = "High" in status_raw or "Non-Compliant" in audit_raw
            
            # Finding Box
            pdf.set_fill_color(255, 255, 255)
            pdf.set_draw_color(220, 220, 220)
            
            # Header line
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(0, 47, 167)
            pdf.cell(0, 8, f"Finding {idx}: Clause on Page {item.get('page_num', 'N/A')}", border='T', new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            
            # Content
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(80, 80, 80)
            pdf.cell(0, 6, "EXTRACTED TEXT:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(100, 100, 100)
            clause_text = clean_text(item.get("clause_text", "N/A"))
            pdf.multi_cell(0, 5, clause_text, border=0)
            pdf.ln(2)
            
            # Analysis Result
            section_id, suggested_fix = extract_section_and_fix(audit_raw)
            
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(0, 0, 0)
            status_label = "NON-COMPLIANT" if is_high else "COMPLIANT"
            status_color = (220, 38, 38) if is_high else (22, 163, 74)
            
            pdf.cell(20, 6, "STATUS: ", new_x=XPos.RIGHT)
            pdf.set_text_color(*status_color)
            pdf.cell(40, 6, status_label, new_x=XPos.RIGHT)
            
            pdf.set_text_color(0, 0, 0)
            pdf.cell(30, 6, "REFERENCE: ", new_x=XPos.RIGHT)
            pdf.set_font("Helvetica", "", 9)
            pdf.cell(0, 6, section_id, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            
            pdf.ln(1)
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(0, 6, "REMEDIATION STEPS:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            pdf.set_font("Helvetica", "", 9)
            pdf.multi_cell(0, 5, suggested_fix, border=0)
            
            pdf.ln(8)

    try:
        pdf.output(output_pdf_path)
        return output_pdf_path
    except Exception as e:
        print(f"Error: {e}")
        return None

if __name__ == "__main__":
    generate_report()

