import json
import os
import re
from fpdf import FPDF
from fpdf.enums import XPos, YPos

# Paths
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
REPORT_JSON = os.path.join(BASE_DIR, "audit_report.json")
OUTPUT_PDF = os.path.join(BASE_DIR, "DPDP_Compliance_Report.pdf")

class PDFReport(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 16)
        # Deep Blue color for Title
        self.set_text_color(20, 40, 90)
        self.cell(0, 10, "DPDP 2023 COMPLIANCE AUDIT REPORT", border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="C")
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        disclaimer = "Generated by AI Compliance Engine. Please consult a legal professional for final verification."
        self.cell(0, 10, disclaimer, border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="C")

def extract_section_and_fix(text: str):
    """Attempt to parse the 'Legal Section' and 'Suggested Correction' out of the generic LLM block."""
    section, fix = "Not explicitly stated", "See detailed analysis"
    
    # Try Regex for Section
    sec_match = re.search(r'(?i)(?:Section|Act Section)[\*:\s]+([0-9a-zA-Z\(\)]+)', text)
    if sec_match:
        section = f"Section {sec_match.group(1)}"
        
    # Try Regex for Suggested Correction or Fix
    fix_match = re.search(r'(?i)(?:Suggested Correction|Fix|Correction)[\*:\s]+(.*)', text, re.DOTALL)
    if fix_match:
        fix = fix_match.group(1).strip()
    else:
        # Fallback: Just return the whole raw text without "**"
        fix = text.replace("**", "").replace("_", "")
        
    return section, fix.replace("**", "")

def generate_report(report_data=None, report_json_path=REPORT_JSON, output_pdf_path=OUTPUT_PDF):
    if report_data is not None:
        data = report_data
    else:
        if not os.path.exists(report_json_path):
            print(f"Error: {report_json_path} not found. Please run an audit first.")
            return None
        with open(report_json_path, 'r', encoding='utf-8') as f:
            data = json.load(f)

    # 1. Calculate Risk Summary
    high_count = sum(1 for item in data if "High" in item.get("status", ""))
    medium_count = sum(1 for item in data if "Medium" in item.get("status", ""))
    low_count = sum(1 for item in data if "Low" in item.get("status", "") or "Reviewed" in item.get("status", ""))

    pdf = PDFReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # 2. Add Risk Summary Section
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, "Risk Summary", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_fill_color(240, 240, 240)
    pdf.set_font("Helvetica", "", 12)
    
    summary_text = (
        f"Total Clauses Reviewed:   {len(data)}\n"
        f"High Risk (Violations):   {high_count}\n"
        f"Medium Risk (Warnings):   {medium_count}\n"
        f"Low Risk (Compliant):     {low_count}"
    )
    pdf.multi_cell(0, 8, summary_text, border=1, fill=True)
    pdf.ln(10)

    # 3. Findings Loop
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Detailed Findings", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(2)

    for item in data:
        # We wrap each finding in an unbreakable block so it won't split across pages!
        with pdf.unbreakable():
            # Determine Status details
            status_text = item.get("status", "Unknown")
            is_high = "High" in status_text or "Non-Compliant" in item.get("audit_result", "")
            
            # Draw Box Background
            pdf.set_fill_color(252, 252, 252) # Light grey box
            
            # Finding Header
            pdf.set_font("Helvetica", "B", 12)
            pdf.set_text_color(0, 0, 0)
            pdf.cell(0, 8, f"Clause #{item.get('clause_id', '?')} (Page {item.get('page_num', '?')})", border='LRT', fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            
            # Original Clause
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 6, "Original Clause:", border='LR', fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            pdf.set_font("Helvetica", "", 10)
            clause_str = item.get("clause_text", "N/A").encode('latin-1', 'replace').decode('latin-1')
            pdf.multi_cell(0, 6, clause_str, border='LR', fill=True)
            
            # Status Box
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(20, 8, "Status: ", border='L', fill=True, new_x=XPos.RIGHT, new_y=YPos.TOP)
            if is_high:
                pdf.set_text_color(220, 20, 20) # Bright RED
                printable_status = "NON-COMPLIANT (HIGH RISK)"
            else:
                pdf.set_text_color(34, 139, 34) # Green
                printable_status = "COMPLIANT / LOW RISK"
                
            pdf.cell(0, 8, printable_status, border='R', fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            pdf.set_text_color(0, 0, 0) # reset to black

            # Parse Analysis
            audit_raw = item.get("audit_result", "")
            section_id, suggested_fix = extract_section_and_fix(audit_raw)
            
            # Legal Section
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(28, 6, "Legal Section: ", border='L', fill=True, new_x=XPos.RIGHT, new_y=YPos.TOP)
            pdf.set_font("Helvetica", "", 10)
            pdf.cell(0, 6, section_id.encode('latin-1', 'replace').decode('latin-1'), border='R', fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            
            # Suggested Fix
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 6, "Suggested Fix / Details:", border='LR', fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            pdf.set_font("Helvetica", "", 10)
            
            # Sanitize fix text for fpdf standard ASCII / Latin-1 renderer
            safe_fix = suggested_fix.encode('latin-1', 'replace').decode('latin-1')
            pdf.multi_cell(0, 6, safe_fix, border='LRB', fill=True)
            
            # Add spacing between boxes
            pdf.ln(6)

    try:
        pdf.output(output_pdf_path)
        print(f"✅ Professional Report generated successfully at: {output_pdf_path}")
        return output_pdf_path
    except Exception as e:
        print(f"❌ Failed to generate PDF: {e}")
        return None

if __name__ == "__main__":
    generate_report()
